services:
  ride-app:
    build: .
    container_name: ride-app
    ports:
      - 8000:8000
      - 5678:5678
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000",
      ]
    env_file:
      - path: ./app/.env
    volumes:
      - .:/code
    depends_on:
      - pgdb
    restart: "always"

  pgdb:
    image: postgres:14
    container_name: pgdb
    ports:
      - 5432:5432
    env_file:
      - path: ./app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
