# Generated by Django 4.1.3 on 2024-08-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='id_ride_event',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
